spring:
  application:
    name: aggregator
  config:
    #import: configserver:http://localhost:8888
    #import: configserver:http://config-server:8888
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://discovery-server:8761/eureka/
      defaultZone: http://${eureka.instance.hostname:discovery-server}:${eureka.instance.port:8761}/eureka/