grpc:
  server:
    port: 59091
server:
  port: 8080
kafka:
  bootstrap.servers: "localhost:9092"
  key_serializer_class: "org.apache.kafka.common.serialization.StringSerializer"
  value_serializer_class: "collector.service.handler.CollectorAvroSerializer"